DBpassword: "1234"
replicaCount: 2
namespace: event-planner
image:
  repository: "006262944085.dkr.ecr.us-east-1.amazonaws.com/tova-portfolio/event-planner"
  tag: "v1.0.17"
  pullPolicy: "Always"

container:
  port: 5000
  protocol: "TCP"

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: "ClusterIP"
  port: 5000