event-planner:
  replicaCount: 2
  namespace: event-planner
  image:
    repository: ""
    tag: ""
    pullPolicy: "Always"

  container:
    port: 5000
    protocol: "TCP"

  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  service:
    type: "ClusterIP"
    port: 5000

mongodb:
  fullnameOverride: ""