apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_ROOT_PASSWORD
      remoteRef:
        key: tova_portfolio_mongodb_credentials
        property: MONGODB_ROOT_PASSWORD

    - secretKey: MONGODB_ROOT_PASSWORD
      remoteRef:
        key: tova_portfolio_mongodb_credentials
        property: MONGODB_ROOT_PASSWORD

