apiVersion: eks.amazonaws.com/v1alpha1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  backendType: secretsManager
  data:
    - secretKey: MONGODB_ROOT_USER
      remoteRef:
        key: tova_portfolio_mongodb_credentials
        property: MONGODB_ROOT_USER
    - secretKey: MONGODB_ROOT_PASSWORD
      remoteRef:
        key: tova_portfolio_mongodb_credentials
        property: MONGODB_ROOT_PASSWORD
