apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  MONGODB_PART_URI: {{ printf "@%s-mongodb-headless:27017/event_db?authSource=admin" .Release.Name }}


