---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    PASSWORD: AgDZe8uZyvjOot02itMNq7Qi2udw+QeBO4y9VyfLSdOQvAL6hUYRSumxuBU8ZzBtPyKnAefdoUtsqkObpNrmrGbuxryOrP++psqH78H2pPruvlfJXmJV0stet7o+uu6Fi2bBUH0EBxuGpyshD7/jwFuA3f86EGtcSEVvInqF5bravIM6X2G/3SFkHerABOLYAC2jR5UHwzUc4tLeQses4tfNfqRA9EEq3YAr0nMIZedFsSdYIwfIrUpgZVATCTymGW3z4/XkBqIewfc6GlnXZTca7NIQCPRyVWZ0t/xW8Glzf4EjG4ksaoHsOFlr9y2zCl4KFo8+g2TRhA5Cf6mzdeOjvdKITbOgmJlUolNuMHHuEj4trYUS4L69oNI4mVYIEW331uZAEr/SBU0cs+hpVXmterk4Sfh0bAztBBIQMxukBbhviM0xsacGTmUEz/mnUwHWifY5GHNhMy9G1+UEBkhBDlP3aM8+CgXis5gk6idd5mF5QMJvXBXDXHV53zmA0TUECQ73oZnzYrq1OrdfeKnTWToyGGMRhia/EtNaT5F2sDGMaqYYezt+ZPdSM8DPipIoEGwnIe+Oyp1YAOCRcomoyCWTtMHNPe6TRVWI1u2zEJeCM1poi5cRC2PBwXc12ECPHM5O5pVWcnbodrgcyikrqnrUM7RmwNFhQ7rviATq9dq0PFrrDnfYcFz4CRJDUxQqq6QJ
    USER: AgAzPULDWJteGcnx3Hj2Kj2CFNfOZ9bFbjplpDfbX6Pko7oYPxm81nwBTYyvWaFtkZwIwIQXmbiaD6tORq/iO/wZIR/hyUOay200vHzQfy+paSNj6RtifG7gT7i3P5CyQrYCpt5/6MzsqdQCMKenufN9u+jwgaCYx/lXMvIxU+owqjHsk0cFCP44u0fzTd9CgzJ4baDBpO59gBE7kUpolZeYLhessY/VXBpceaivPTEo+48oYsZDIxl2ycvJX7+y3NNA0w6nH23KYwvn+5R4HyGrSHvvXJIuvjBc/cwIZkaLwkSf+j6QQnORTz0oBYqvTidYNZ+kvuU+WM2EaenkmNHstW1HqvhU08DECMxpkqoiqyeP3lLkz17ZdH25uAASaI/CtI5x1VcHT6nFdaPK0JHWbUM5M6/eNe8PHdK2SNJRRYs3F1GxSS8OVNIX3pPVGDeW2PX2wto7Is7lRsxZ/S1mPbO/ezwKvbSumST6NDGOp2O82JCq/+aNxOKi4H42YH3xsMkqaeJ+6vaS+NkfVPMCy8KoW95vQBXOhNoCw2LrYcWd/prAzyYHShLeKiOP8v6bgRqzBciKy9BLjGS5qtxEoMo67H7UP+VPSAfvYNqOZ6jZnD/Fb4AcCFlcwawADI6lQZzCtJCnhBxTVFbyqti6uMirWWDtuYDMVEcWNLJWNXpi9PsTIYLKH6qV7VnCwM557WfH
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-secret
      namespace: {{ .Values.namespace }}
