apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  MONGO_URI: {{ printf "mongodb://root:%s@event-planner-mongodb-headless:27017/event_db?authSource=admin&replicaSet=rs0" .Values.DBpassword | b64enc }}