logLevel: info
config:
    service: |
        [SERVICE]
            Daemon Off
            Flush 1
            Log_Level info
            Parsers_File /fluent-bit/etc/parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020
            Health_Check On

    inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*event*.log
            Tag kube.*
            Parser docker
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On

    filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On

        [FILTER]
            Name grep
            Match kube.*
            Regex $kubernetes['labels']['app'] ^event

    outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            Host elasticsearch-master
            Port 9200
            Logstash_Format On
            Logstash_Prefix event-apps
            Index event-apps
            Type _doc
            Retry_Limit False
            Suppress_Type_Name On


    customParsers: |
        [PARSER]
            Name docker_no_time
            Format json
            Time_Keep Off
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%L
