apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: event-planner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KleinTova/portfolio-gitops-config.git'
    path: event-planner-umbrella-chart
    targetRevision: main
    helm:
        valueFiles:
          - - ../../config/dev/event-planner.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: event-planner

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
