apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: event-planner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/KleinTova/portfolio-gitops-config.git'
      path: event-planner-umbrella-chart
      targetRevision: main
      helm:
          valueFiles:
            - $values/config/dev/event-planner.yaml
    - repoURL: "git@github.com:KleinTova/portfolio-gitops-config.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: event-planner

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
