apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  name: external-secrets
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: 'https://charts.external-secrets.io'
      chart: external-secrets
      targetRevision: 0.14.2
    helm:
          valueFiles:
            - $values/config/dev/external-secrets.yaml
    - repoURL: "git@github.com:KleinTova/portfolio-gitops-config.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-configs
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/KleinTova/portfolio-gitops-config.git'
    targetRevision: main
    path: external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
