apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: filebeat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: 'https://helm.elastic.co'
      targetRevision: 8.5.1
      chart: filebeat
      helm:
          valueFiles:
            - $values/config/dev/filebeat.yaml
    - repoURL: "git@github.com:KleinTova/portfolio-gitops-config.git"
      targetRevision: HEAD
      ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
