apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: kibana
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://helm.elastic.co'
    chart: kibana
    targetRevision: 8.5.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
