replicas: 2
minimumMasterNodes: 1
imageTag: 8.6.2
volumeClaimTemplate:
  storageClassName: "gp2"
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "750m"
    memory: "2Gi"
esJavaOpts: "-Xms512m -Xmx512m"